# Generated by Django 3.0.2 on 2020-01-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200130_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reputation',
        ),
    ]
