# Generated by Django 3.0.2 on 2020-01-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200128_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=20)),
                ('humidity', models.CharField(max_length=20)),
                ('dust', models.CharField(max_length=20)),
            ],
        ),
    ]
