# Generated by Django 3.0.2 on 2020-01-29 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20200129_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensormodel',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
