# Generated by Django 3.0.2 on 2020-01-29 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_sensormodel_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensormodel',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
