# Generated by Django 3.0.2 on 2020-01-29 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20200129_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensormodel',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterField(
            model_name='sensormodel',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
