# Generated by Django 3.0.2 on 2020-01-29 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20200130_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensormodel',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
