# Generated by Django 3.0.2 on 2020-01-29 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20200130_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensormodel',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
