# Generated by Django 3.0.2 on 2020-01-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_auto_20200130_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={},
        ),
    ]
