# Generated by Django 3.0.2 on 2020-01-21 13:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200121_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
