# Generated by Django 3.0.2 on 2020-01-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_locationpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationPost',
        ),
    ]
