# Generated by Django 3.0.2 on 2020-01-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='geom',
        ),
    ]
