# Generated by Django 3.0.2 on 2020-01-22 19:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
