# Generated by Django 3.0.2 on 2020-01-22 19:25

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(27.6828417, 85.3178166), srid=4326)),
        ),
    ]
