# Generated by Django 3.0.2 on 2020-01-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200122_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='geometry',
        ),
    ]
