# Generated by Django 3.0.2 on 2020-01-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200130_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='gallery/'),
        ),
    ]
